
#TODO: 
# - Add a step to run tests after building the workspace.
# - Add a step to upload the built artifacts to a release or an artifact storage.
# - Add a step to notify the team about the build status (success/failure).
# - Add a step to clean up the workspace after the build is complete.
# - Add a step to check for code style and formatting issues.
# - Add a step to check for dependencies and install them if necessary.

name: Onboard ROS Build
on:
  push:
    branches: ["main"] # TODO: apply to all branch when commit/ change to "main", "feature/**" or "develop" branch
  pull_request:
    branches: ["main"] # TODO: change to main branch when commit
jobs:
  ros2-humble:
    runs-on: ubuntu-latest
    container: ros:humble-ros-core-jammy  # Use the official ROS 2 Humble Docker image, tahnks god it works now
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2 environment
        working-directory: $GITHUB_WORKSPACE
        run: |
          echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV
          source /opt/ros/humble/setup.bash

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-colcon-common-extensions
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Check code style (ament_lint)
        run: |
          colcon lint

      - name: Build ROS 2 workspace
        run: |
          colcon build
          source install/setup.bash

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ros2-workspace-artifacts
          path: install/

      - name: Clean up workspace
        run: |
          rm -rf build/ install/ log/
