name: Onboard ROS Build

on:
  push:
    branches: ["main"] # TODO: expand to ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main"]

jobs:
  ros2-humble:
    runs-on: ubuntu-latest
    container: ros:humble-ros-core-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2 environment
        run: |
          echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV
          source /opt/ros/humble/setup.bash

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            python3-colcon-common-extensions \
            python3-pip
          pip3 install -U flake8  # Optional: for Python linting
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Check code style (ament_lint)
        run: |
          colcon lint || echo "Linting warnings found"

      - name: Check Python formatting (flake8)
        run: |
          flake8 src/ || echo "Python style issues found"

      - name: Build ROS 2 workspace
        run: |
          colcon build
          source install/setup.bash

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ros2-workspace-artifacts
          path: install/

      - name: Notify team on failure
        if: failure()
        run: |
          echo "Build failed! Notify team via Slack, email, or GitHub comments."
          # Here you could integrate with a Slack webhook or other service.

      - name: Clean up workspace
        run: |
          rm -rf build/ install/ log/
