name: Onboard ROS Build

on:
  push:
    branches: ["main"] # TODO: expand to ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main"]

jobs:
  ros2-humble:
    runs-on: ubuntu-latest
    container: ros:humble-ros-core-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2 environment
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          echo "ROS environment sourced."

      - name: Install dependencies
        shell: bash
        run: | # installing system dependencies for running rover using ros2 humble
          apt-get update && apt-get install -y \
            # python3-colcon-common-extensions \
            python3-pip \
            python3-setuptools \
            python3-vcstool \
            git
          pip3 install -U \
            flake8 \
            ament-lint
          echo "Dependencies installed."

      - name: Check code style (ament_lint)
        run: |
          colcon lint || echo "Linting warnings found"

      - name: Check Python formatting (flake8)
        run: |
          flake8 src/ || echo "Python style issues found"

      - name: Build ROS 2 workspace
        run: |
          colcon build
          source install/setup.bash

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ros2-workspace-artifacts
          path: install/

      - name: Notify team on failure
        if: failure()
        run: |
          echo "Build failed! Notify team via Slack, email, or GitHub comments."
        # Here you could integrate with a Slack webhook or other service.

      - name: Clean up workspace
        run: |
          rm -rf build/ install/ log/
